{
 "title": "Blockchain",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "network",
    "label": "Network",
    "query": "SHOW TAG VALUES FROM system WITH KEY=network"
   },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM system WITH KEY=host"
   }
  ]
 },
 "panels": [
  {
   "title": "Transactions Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"transactions\") AS \"transactions\" FROM \"bc_block\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) GROUP BY time(3s) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions #",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"transactions\")  FROM \"bc_block\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Api Requests Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"ok_requests\" FROM \"bc_request\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"status\"='OK' GROUP BY time(1s) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"error_requests\" FROM \"bc_request\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"status\"='ERR' GROUP BY time(1s) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ok Api Requests #",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"ok_requests\" FROM \"bc_request\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"status\" = 'OK'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Err Api Requests #",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"ok_requests\" FROM \"bc_request\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"status\" = 'ERR'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "content": "<center><p>Act. Participation Rate</p></center>\n<center>(latest 200 blocks)</center>\n<center><h1>&#8675;</h1></center>"
  },
  {
   "title": "Blocks Production",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"block\")  FROM \"bc_block\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/)  AND \"time\" < now() - 15s GROUP BY time(3s) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Average Block Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"latency\") AS \"avg latency\" FROM \"bc_block\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) GROUP BY time(3s) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Api Requests grouped by \"Api && Method\"",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"status\") AS \"ok\" FROM \"bc_request\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"status\" = 'OK'  GROUP BY api , method",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (count(\"block\") / 200) * 100 FROM \"bc_block\" WHERE (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND time > now() - 615s AND time < now() - 15s",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Missed blocks grouped by \"Witness\"",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(log_time)  FROM \"bc_missed_block\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) GROUP BY witness",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warnings & Errors Counter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"type\") AS \"errors\" FROM \"bc_log\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"type\"='error' GROUP BY time(1s) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"type\") AS \"warnings\" FROM \"bc_log\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"type\"='warn' GROUP BY time(1s) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors #",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"type\") FROM \"bc_log\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"type\"='error'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Warnings #",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"type\") AS \"errors\" FROM \"bc_log\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"type\"='warn'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Blocks",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"block\", \"transactions\", \"latency\", \"witness\" FROM \"bc_block\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"msg\" FROM \"bc_log\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/)  AND \"type\" = 'error' ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest Warnings",
   "type": "table",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"msg\" FROM \"bc_log\" WHERE $timeFilter AND (\"network\" =~ /^$network$/) AND (\"host\" =~ /^$server$/) AND \"type\"='warn' ORDER BY time DESC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}